version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:   #para hacer el auto compile
      - /app/node_modules
      - .:/app
  tests: 
    build:
        context: .
        dockerfile: Dockerfile.dev
    volumes:   #para hacer el auto compile
        - /app/node_modules
        - .:/app
    command: ["npm", "run", "test"]   #overwrite command


  #dos containers uno para subir el web y el otro para los tests